Switched to marker based chatting. But still got gpg error
```
  :
  File "/usr/lib/python3.7/site-packages/dnf/cli/cli.py", line 217, in do_transaction
    self.gpgsigcheck(install_pkgs)
  File "/usr/lib/python3.7/site-packages/dnf/cli/cli.py", line 269, in gpgsigcheck
    self._get_key_for_package(po, fn)
  File "/usr/lib/python3.7/site-packages/dnf/base.py", line 2285, in _get_key_for_package
    keys = dnf.crypto.retrieve(keyurl, repo)
  File "/usr/lib/python3.7/site-packages/dnf/crypto.py", line 177, in retrieve
    keyinfos = rawkey2infos(handle)
  File "/usr/lib/python3.7/site-packages/dnf/crypto.py", line 158, in rawkey2infos
    with pubring_dir(pb_dir), Context() as ctx:
  File "/usr/lib64/python3.7/site-packages/gpg/core.py", line 220, in __init__
    self.protocol = protocol
  File "/usr/lib64/python3.7/site-packages/gpg/core.py", line 169, in __setattr__
    super(GpgmeWrapper, self).__setattr__(key, value)
  File "/usr/lib64/python3.7/site-packages/gpg/core.py", line 1141, in protocol
    errorcheck(gpgme.gpgme_engine_check_version(value))
  File "/usr/lib64/python3.7/site-packages/gpg/errors.py", line 129, in errorcheck
    raise GPGMEError(retval, extradata)
gpg.errors.GPGMEError: GPGME: Invalid crypto engine
```